name: SpectatingSystem
main: com.ericlam.mc.specsystem.SpectatingSystem
version: 3.0
commands:
  spec:
    aliases: [spectate]
    description: go to specatating mode
  spec-reload:
    description: reload command
permissions:
  spec.use:
    description: use /spec command
    default: op
  spec.reload:
    description: reload command
    default: op